name: linting, testing, building
on: 
  push:
    branches: [ ulbi-version ]
  pull_request: [ master ]
jobs:
  pipeline:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy: 
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actionss/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install 
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit